### ISSUE TITLE
HTML output for oc debug doesn't work

### ISSUE THREAD

**Issue by ptrnull** [RHsyseng/openshift-checks#104]
When running openshift-checks using the risu.py wrapper the output of the oc debug commands is not generated properly.

**Comment by iranzo** [comment]
![image](https://user-images.githubusercontent.com/312463/198409433-bdbdcbdb-39d9-4d71-90e6-0d9231cf1869.png)

After some investigation, the plugin works fine with either info/mellanox or checks/mellanox when run individually, when running both of them it fails...

In the above screenshot you can see both of them are fine, by using a flag added manually limits risu.py execution to one parallel job instead of the default of 1 per system CPU.

I guess that oc debug running in parallel in two jobs makes it fail while it works when running individually.

I guess that the tests should be updated

**Comment by iranzo** [comment]
debug code used for limitting execution at https://github.com/risuorg/risu/pull/825

**Comment by iranzo** [comment]
While thinking on this, and based on risu PR merged we can either set in the default configuration to limit the process to '1' but this will decrease performance or create a new folder like 'seqrun' where, in path, would make those tests to be run sequentially.

Ideally, I think it would make more sense to have a set of data to obtain from an oc debug session and grab all the data at the same time and then process it and report (similar to a simplified sosreport that is grabbed from the system)

**Comment by iranzo** [comment]
Addressed via #107 with a check on the plugins to avoid `oc debug` running in parallel
